### PR TITLE
Support windows

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@PrimozGodec Seems like it works 🎉 , I'll enable everything else again to see whether we're good to go.

**Comment by PrimozGodec** [comment]
I think that conflicts have something to do with `cmake` in `r-xgboost`. I have compared the recipe with https://github.com/conda-forge/xgboost-feedstock/pull/59 where macOS and Linux build without error. There `cmake` was committed. I do not know if it is a correct solution but it seems it works.

**Comment by xhochy** [comment]
Using `mambabuild` locally I get:

```
Mamba failed to solve:
 - python_abi 3.9.* *_cp39
 - libcxx >=11.0.1
 - py-xgboost 1.3.0 py39_1
 - llvm-openmp >=11.0.1
 - python >=3.9,<3.10.0a0

with channels:

The reported errors are:
   Encountered problems while solving.
   Problem: nothing provides requested py-xgboost 1.3.0 py39_1
```

**Comment by xhochy** [comment]
@PrimozGodec I'm adding myself as a maintainer in this PR, should I also add you? (Latest commit is green, so I would mark it as ready for review).

**Comment by xhochy** [comment]
@conda-forge/xgboost This is ready for the merge button!

**Comment by PrimozGodec** [comment]
@xhochy thank you for making this possible. :)

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Uwe! 😄

**Pull request merged**
