### PR TITLE
ENH enable openmp on osx

### LINKED ISSUE #1: ENH handle OpenMP on linux and mac osx
So right now, the OpenMP support between linux and osx is spotty.
1. OSX has no support for OpenMP.
2. If the proper libraries are not in the linker path for OpenMP on linux, then the recipe will fail.

I think the easiest way to fix this would be to compile with conda's `gcc` for osx only and then include `libgcc` as a run dependence. 

See [this](https://github.com/conda-forge/staged-recipes/pull/2628) PR for osx and this [comment](https://github.com/conda-forge/staged-recipes/pull/2573#discussion_r107445878) from @jakirkham.

### PR DESCRIPTION
**Pull request by beckermr**
I don't expect to merge this yet, but starting work now.

Closes #1

### CODE REVIEW

**Comment by beckermr** [comment]
@jakirkham Thanks again for all the help! The various OpenMP related changes are collected here in this PR. Take a look when you have time. No rush!

**Comment by beckermr** [comment]
@jakirkham It looks the various clang and openmp related recipes have been merged. Should we redo this recipe to enable openmp on OSX with those tools, or are we OK with this recipe as is? 

I rebuilt it and it still passes all of the tests.

**Comment by jakirkham** [comment]
It's definitely an interesting approach to consider. The fact that the LLVM toolchain is supported through packages in `conda-forge` and is a reasonably recent version definitely makes it an attractive alternative to `gcc`. It's also a bit more friendly with UCRT on Windows, which is definitely a plus. I tried building one of my dependencies that uses OpenMP with the LLVM toolchain and was able to run all tests without issues. So it's certainly worth exploring.

**Comment by beckermr** [comment]
OK. @jakirkham. I am closing this in favor of #4. Hopefully using clang will help with windows (#3) as you suggest!

**Pull request closed without merging**
