### PR TITLE
update to 0.81

### PR DESCRIPTION
**Pull request by bgruening**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
I believe the build number needs to be set to 1000? We might want to update the PR instructions in conda-smithy.

**Comment by bgruening** [comment]
@beckermr I can do this. I don't think we need to update the instructions as the build-number will go back to 0 as soon as the big GCC7 migration is done. But for now, I'm just curious if it still builds ... I fear that we need to update the patches :(

**Comment by beckermr** [comment]
Yeah the patches...

These were inherited from the defaults build when I merged that in. We need to submit them upstream.

**Comment by bgruening** [comment]
wow, that was easy :)

**Pull request merged**
