### PR TITLE
Update macOS build

### PR DESCRIPTION
**Pull request by jakirkham**
As we recently published new compilers for macOS, this updates the xgboost build to use the new macOS compilers.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/xgboost-feedstock/issues/32
Closes https://github.com/conda-forge/xgboost-feedstock/pull/33

### CODE REVIEW

**Comment by jakirkham** [comment]
Do we know what's up with the R failure?

```R
+ Rscript test-r-xgboost.r
Loading required package: xgboost
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘xgboost’
Error in find.package(package, lib.loc, verbose = verbose) : 
  there is no package called ‘xgboost’
Calls: data -> find.package
Execution halted
Tests failed for r-xgboost-0.90-r36h4a8c4bd_3.tar.bz2 - moving package to /usr/local/miniconda/conda-bld/broken
```

**Comment by beckermr** [comment]
If you look further up, something in the r-build failed when it could not find a library: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=84089&view=logs&jobId=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&taskId=4a56039b-7269-50ae-de7a-538e91e6de06&lineStart=1272&lineEnd=1273&colStart=1&colEnd=1

```
** R
** data
** demo
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/miniconda/conda-bld/xgboost_1571965060202/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/stringi/libs/stringi.dylib':
  dlopen(/usr/local/miniconda/conda-bld/xgboost_1571965060202/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/stringi/libs/stringi.dylib, 6): Library not loaded: @rpath/libicui18n.64.dylib
  Referenced from: /usr/local/miniconda/conda-bld/xgboost_1571965060202/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/stringi/libs/s
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘xgboost’
```

**Comment by beckermr** [comment]
@conda-forge/r @conda-forge/r-stringi Do you understand the library loading issue in the comment above?

**Comment by beckermr** [comment]
Hmmmm. On OSX the solver is picking up icu 58.2 even though conda-forge has it globally pinned to 64.2. Something somewhere has not been updated for that pinning maybe?

**Comment by beckermr** [comment]
Also it appears we are getting r-base from defaults which doesn't seem right at all.

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
OK. Something somewhere in the r-base 3.6 build is depending on icu 58.2 and needs to be rebuilt for 64.X which is the current pinning. IDK where, but it will need to be tracked down by hand.

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@jakirkham ^ please select this option

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by beckermr** [comment]
I think we need to rebuild r-base. It is on the osx compilers version 4. Doing that now. https://github.com/conda-forge/r-base-feedstock/pull/111

**Comment by jakirkham** [comment]
Ok sounds good.

**Comment by jakirkham** [comment]
> I tried to re-render for you, but it looks like I wasn't able to push to the update_macos_bld branch of jakirkham-feedstocks/xgboost-feedstock. Did you check the "Allow edits from maintainers" box?

FWIW this is already checked. So not sure what's up here.

cc @conda-forge/core

**Comment by isuruf** [comment]
Did you check the logs?

**Comment by beckermr** [comment]
Which logs? Idk where the bot logs are.

**Comment by isuruf** [comment]
It's not public, but @jakirkham has access.

**Comment by beckermr** [comment]
Closing due to #37

**Comment by jakirkham** [comment]
Thanks. Have pulled out one piece that may be worth including as PR ( https://github.com/conda-forge/xgboost-feedstock/pull/38 ).

**Pull request closed without merging**
