### PR TITLE
add(meta): try to build 1.4.2 for python36

### PR DESCRIPTION
**Pull request by FernandezMathieu**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@FernandezMathieu Please mention here what you are trying to achieve instead of opening/closing PRs.

**Comment by FernandezMathieu** [comment]
> @FernandezMathieu Please mention here what you are trying to achieve instead of opening/closing PRs.

I have conda environment in python 3.6.5 where i try to install XgBoost for CPU use only. 
The last version of XgBoost using python 3.6 seem to be Xgboost 1.4.2. So here i try to build xgboost 1.4.2 for python 3.6 with the build name formatted like this : `cpu_py36xxxx`

**Comment by xhochy** [comment]
If the build is already available on conda-forge, why do you want to rebuild anything here? As mentioned, rerenders will remove 3.6 anyways.

**Comment by FernandezMathieu** [comment]
@xhochy the build name for 1.4.2 version of xgboost is not formatted with the `cpu_py[version]` like the others versions do. 
It prevents us from filtering the 1.4.2 with the same build flag as other versions.  

`conda install xgboost=*=*cpu*` don't work.

**Comment by FernandezMathieu** [comment]
So @xhochy the need sound like acceptable to you ? Can i continue my work here ?

**Comment by xhochy** [comment]
Neither are all over releases except 1.5.2. If you wanted this to work, you would need to rebuild all past versions.

**Comment by jakirkham** [comment]
Is this something you are still interested in @FernandezMathieu?

**Pull request closed without merging**
