### PR TITLE
Switch to using CMake for the build

### PR DESCRIPTION
**Pull request by jakirkham**
This switches the build over to using CMake. Should make it easier to follow along with the build instructions provided by the xgboost developers. Also should make it easier to enable different customizations and plugins should they be of interest.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/xgboost-feedstock/issues/27

### CODE REVIEW

**Comment by jakirkham** [comment]
Alright the Linux build now passes.

The macOS builds crashes after building `objxgboost`. Not sure what is going on there.

**Comment by beckermr** [comment]
Cool! Is now a good time to enable windows too? I have had this issue open for a while and as soon as we move to cmake all of my progress (from copying other sources) will be lost.

**Comment by jakirkham** [comment]
I'd prefer to focus on getting the currently supported OSes building in this PR if that is ok.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by beckermr** [comment]
@conda-forge-admin, please re-render.

**Comment by beckermr** [comment]
@conda-forge-admin, please re-render

**Comment by beckermr** [comment]
I removed the py2k builds.

**Comment by jakirkham** [comment]
Thanks for the reminder. Yeah I recall that PR in. Sorry for all the bot noise. Figured we should dust this one off and see if things have gotten better since the 0.90 release.

**Comment by beckermr** [comment]
Sounds good. I really want windows to work so time to try again indeed!

**Comment by jakirkham** [comment]
Yeah I'm hoping we can share some downstream changes with conda-forge. Unfortunately that's difficult to do without first getting the build to use CMake.

**Comment by beckermr** [comment]
The cmake build runs fine if I checkout the repo locally. IDK what is going on in the CI which is pretty frustrating. I am stripping back all of the changes and patches to try and start fresh on this.

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks so much for all the hard work sorting out the macOS build errors and getting this in, @beckermr! 😄

**Pull request merged**
