### PR TITLE
Update to version 1.0.2

### PR DESCRIPTION
**Pull request by ksangeek**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ksangeek** [comment]
Hello,
I was able to build the conda package for the latest version `1.0.2` of xgboost (python) in my Linux environment and thought it would be good to update that in `conda-forge` for a wider audience to use.
Out of the three patches used for the earlier conda package, one of them `0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch` did not apply and I am not sure if that is still required.

If anyone has any suggestions on what other work is needed to make this work for complete, I can get that done. Thanks.

**Comment by beckermr** [comment]
Yeah this recipe is def in need of some TLC. I'd take a look in the new build scripts and see what they are doing these days. The patches were to unbundle the C++ library from the R and Python bindings.

**Comment by ksangeek** [comment]
@conda-forge-admin, please rerender

**Comment by ksangeek** [comment]
Hi @beckermr, after updating the patch `0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch` for the latest release, the earlier issue has been resolved and now the packages are building fine.

**Comment by beckermr** [comment]
Would you like to be a maintainer on this recipe @ksangeek?

**Comment by ksangeek** [comment]
> Would you like to be a maintainer on this recipe @ksangeek?

@beckermr yes, please

**Comment by beckermr** [comment]
Great! Add your username to the maintainers section in the meta.yaml and then we can merge! Thank you!

**Comment by ksangeek** [comment]
Thank you @beckermr

**Comment by beckermr** [comment]
Thank you!

**Pull request merged**
