### PR TITLE
Fix patch to close #46

### LINKED ISSUE #46: Issue installing py-xgboost as a dependency from conda-forge
Issue:

I am trying to install py-xgboost as a dependency of another package over at bioconda (https://github.com/bioconda/bioconda-recipes/pull/20014). However, even though xgboost is set as a dependency for the package and is installed during setup, the build fails with the error: 
`pkg_resources.DistributionNotFound: The 'xgboost' distribution was not found`

I can reproduce if I install py-xgboost with: 
```
$ conda create -n test_install py-xgboost
$ conda activate test_install
```
Then the xgboost package is not known by python to be installed:
```
(test_install)$ pip freeze
certifi==2019.11.28
joblib==0.14.1
numpy==1.17.5
scikit-learn==0.22.1
scipy==1.4.1
```
Importing the package works fine (`python -c 'import xgboost'`) though. If I install directly with pip, the package is known:
``` 
(test_install)$ pip install xgboost
(test_install)$ pip freeze
certifi==2019.11.28
joblib==0.14.1
numpy==1.17.5
scikit-learn==0.22.1
scipy==1.4.1
xgboost==0.90
```

The problem specifically arises when installing another python package via conda, which has xgboost in "install_requires". Then, the package somehow thinks that xgboost is not available and therefore fails on install.

It was suggested in the bioconda issue that the problem might arise due to a missing .dist-info directory for xgboost (?). I hope you can guide on how to solve this!

Best Mette

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/mbentse/.conda/envs/test_install:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libxgboost                0.90                 he1b5a44_4    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.5           py38h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pip                       20.0.2                   py38_0    conda-forge
py-xgboost                0.90                     py38_4    conda-forge
python                    3.8.1                h357f687_2    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scikit-learn              0.22.1           py38hcdab131_1    conda-forge
scipy                     1.4.1            py38h921218d_0    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.1                   py38_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

```
</details>

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/xgboost-feedstock/issues/46

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
Closes #46 by generally fixing the python package.

**Comment by dpryan79** [comment]
@aldanor @jakirkham @beckermr This is ready for review

**Comment by jakirkham** [comment]
Would it be possible to also submit this patch upstream? 🙂

**Comment by beckermr** [comment]
I don’t follow the patch but that’s ok. This recipe has really moved from upstream so we should be thinking about that.

**Comment by dpryan79** [comment]
I'm not sure the patch is relevant upstream, it just prevents vendoring a library that's a subpackage in conda-forge. Outside of conda you would very much want the unpatched behavior.

**Comment by jakirkham** [comment]
In that case, would you mind raising an issue? Ideally we wouldn't need this patch and we could just configure xgboost to build with the external library we intend.

**Comment by dpryan79** [comment]
Sure, done https://github.com/dmlc/xgboost/issues/5386

**Comment by jakirkham** [comment]
cc @hcho3 (for awareness)

**Comment by jakirkham** [comment]
I think this got handled in PR ( https://github.com/conda-forge/xgboost-feedstock/pull/50 ). Could you please recheck @dpryan79? 🙂

**Comment by trivialfis** [comment]
Please take a look into https://github.com/dmlc/xgboost/pull/6362 .

**Comment by jakirkham** [comment]
Thanks Jiaming! 😄

**Pull request closed without merging**
