### PR TITLE
Cross-compile for the arches

### LINKED ISSUE #72: conda-forge CI error
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
https://conda-forge.org/status/#armosxaddition -> Bot-Error 

xgboost (0) Error: bot error (bot CI job): master: Traceback (most recent call last): File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py", line 1122, in main migrator_uid, pr_json = run( File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py", line 226, in run eval_cmd( File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py", line 261, in eval_cmd c.check_returncode() File "/usr/share/miniconda/envs/run_env/lib/python3.9/subprocess.py", line 460, in check_returncode raise CalledProcessError(self.returncode, self.args, self.stdout, subprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1. 

Seems it's broken and not available due to upper error.

(base) jc@jcs-Mac-mini xgboost-feedstock % conda install xgboost
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - xgboost

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

<br/>
Environment (<code>conda list</code>):
<details>

```
(base) jc@jcs-Mac-mini xgboost-feedstock % conda list
# packages in environment at /opt/homebrew/Caskroom/miniforge/base:
#
# Name                    Version                   Build  Channel
astroid                   2.5.1            py39h2804cbe_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
blinker                   1.4                        py_1    conda-forge
boolean.py                3.7                        py_0    conda-forge
brotlipy                  0.7.0           py39h46acfd9_1001    conda-forge
bzip2                     1.0.8                h27ca646_4    conda-forge
c-ares                    1.17.1               h27ca646_1    conda-forge
ca-certificates           2020.12.5            h4653dfc_0    conda-forge
certifi                   2020.12.5        py39h2804cbe_1    conda-forge
cffi                      1.14.5           py39h702c04f_0    conda-forge
chardet                   3.0.4           py39h0caf4da_1008    conda-forge
conda                     4.9.2            py39h2804cbe_0    conda-forge
conda-build               3.21.4           py39h2804cbe_0    conda-forge
conda-forge-pinning       2021.03.22.11.12.50      hd8ed1ab_0    conda-forge
conda-package-handling    1.7.2            py39h51e6412_0    conda-forge
conda-smithy              3.9.0              pyhd8ed1ab_0    conda-forge
cryptography              3.4.6            py39h73257c9_0    conda-forge
curl                      7.75.0               hb25ae9e_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
deprecated                1.2.10             pyh9f0ad1d_0    conda-forge
expat                     2.2.10               h9f76cd9_0    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
gettext                   0.19.8.1          hea66d9f_1005    conda-forge
git                       2.30.2          pl5320hf5a5368_0    conda-forge
gitdb                     4.0.5              pyhd8ed1ab_1    conda-forge
gitpython                 3.1.14             pyhd8ed1ab_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       68.1                 h17758a7_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
isodate                   0.6.0                      py_1    conda-forge
isort                     5.7.0              pyhd8ed1ab_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
krb5                      1.17.2               h17618d6_0    conda-forge
lazy-object-proxy         1.5.2            py39h46acfd9_1    conda-forge
libarchive                3.5.1                h2abb879_1    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.75.0               h222edf9_0    conda-forge
libcxx                    11.1.0               h168391b_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_20    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_20    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
liblief                   0.10.1               hb904e53_2    conda-forge
libnghttp2                1.43.0               hf3018f0_0    conda-forge
libopenblas               0.3.12          openmp_h2ecc587_1    conda-forge
libprotobuf               3.15.6               habe5f53_0    conda-forge
libssh2                   1.9.0                hb80f160_6    conda-forge
libxml2                   2.9.10               h8f9ca65_3    conda-forge
license-expression        1.2                        py_0    conda-forge
llvm-openmp               11.1.0               hb3022d6_0    conda-forge
lz4-c                     1.9.3                h9f76cd9_0    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
markupsafe                1.1.1            py39h46acfd9_3    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
more-itertools            8.7.0              pyhd8ed1ab_0    conda-forge
msrest                    0.6.21             pyh44b312d_0    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
numpy                     1.20.1           py39h69a04d8_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
onnx                      1.8.1            py39h93768c6_2    conda-forge
openssl                   1.1.1j               h27ca646_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pcre                      8.44                 hb904e53_0    conda-forge
perl                      5.32.0               h27ca646_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.7.0              pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py39h2804cbe_4    conda-forge
protobuf                  3.15.6           py39h93dc1e2_0    conda-forge
psutil                    5.8.0            py39h46acfd9_1    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
py-lief                   0.10.1           py39h9336629_2    conda-forge
pycosat                   0.6.3           py39h46acfd9_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py39h51e6412_1005    conda-forge
pygithub                  1.54.1             pyhd3deb0d_0    conda-forge
pyjwt                     2.0.1              pyhd8ed1ab_0    conda-forge
pylint                    2.7.2            py39h2804cbe_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_3    conda-forge
pytest                    6.2.2            py39h2804cbe_0    conda-forge
python                    3.9.2           hcbd9b3a_0_cpython    conda-forge
python-libarchive-c       2.9              py39h2804cbe_2    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39h46acfd9_0    conda-forge
readline                  8.0                  hc8eb9b7_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h1f0153e_1    conda-forge
ruamel.yaml               0.16.12          py39h46acfd9_2    conda-forge
ruamel.yaml.clib          0.2.2            py39h46acfd9_2    conda-forge
ruamel_yaml               0.15.80         py39h46acfd9_1004    conda-forge
scipy                     1.6.1            py39h73ea49b_0    conda-forge
scrypt                    0.8.17           py39h0bed37e_1    conda-forge
setuptools                49.6.0           py39h2804cbe_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.34.0               h6d56c25_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tqdm                      4.57.0             pyhd8ed1ab_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wrapt                     1.12.1           py39h46acfd9_3    conda-forge
xgboost                   1.3.3                    pypi_0    pypi
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h642e427_0    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
zstd                      1.4.9                h5b28eab_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
(base) jc@jcs-Mac-mini xgboost-feedstock % conda info

     active environment : base
    active env location : /opt/homebrew/Caskroom/miniforge/base
            shell level : 1
       user config file : /Users/jc/.condarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
                          /Users/jc/.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.9.2.final.0
       virtual packages : __osx=11.2.3=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/homebrew/Caskroom/miniforge/base  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/miniforge/base/pkgs
                          /Users/jc/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniforge/base/envs
                          /Users/jc/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.9.2 Darwin/20.3.0 OSX/11.2.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #72 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge/xgboost This is extremely hard to solve because we build everything in a single recipe and run into either cross-compiling or CI runtime issues. Would there be opposition to splitting this into three feedstock (C++, Python, R)?

**Comment by hcho3** [comment]
I approve the splitting of the feedstock. (I am one of the maintainers of XGBoost.)

**Comment by isuruf** [comment]
@xhochy what are the issues with cross compiling?

**Comment by xhochy** [comment]
The most major issue here has the root cause that we cannot cross compile for PyPy. Thus I introduced some skips for that and rerendered. This then also had an effect on Windows builds, I don't fully understand.

For ppc64le and aarch64, we cannot build on Travis/drone as it takes too long. Thus the need to cross-compile at all.

In contrast to other feedstocks, the setting is more complicated as we build some of the outputs multiple times during a single build. The number of builds differs though per output.

**Comment by xhochy** [comment]
Closing as I don't have the time currently.

**Pull request closed without merging**
